// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2026 rakwahye
/** @file playlist.h
 * @brief Preset playlist.
 *
 * The ordered preset list and its selection state: blacklists, list-file
 * I/O, and preset-age auto-advance. Scans the preset directory from the
 * shared presets slice. */

#ifndef PLAYLIST_H
#define PLAYLIST_H

#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

struct playlist_config {
	int shuffle; // 1 = shuffle, 0 = sequential
	char auto_load[256];
	double duration; // Auto-advance interval (s), 0 = off
};

void playlist_init(void);

/** Playlist state bring-up. Runs before the engine so it can be
 * configured from the selected preset. */
void playlist_bringup(void);

/** Deferred initial load. Call after the visualizer is initialized. */
void playlist_load_initial(void);

struct rt;
/** Called by `apply_pending` for every PENDING_* it does not own. Sole
 * playlist mutator runs here, on the GL thread. */
void playlist_apply_pending(struct rt *rt, int action);

/** playlist's IPC verb handler. Owns the playlist-only command vocab.
 * Receives the raw command line and the pending mailbox. Mutations
 * post to the mailbox, reads answer from the snapshot.
 * @returns 1 if the verb was handled, 0 to let the caller try other handlers. */
int playlist_ipc_command(struct rt *mbox, const char *line, char *reply,
                         int reply_len);

/** Re-apply playlist's config slice (shuffle). Called from init and after a
 * config reload re-parses it. auto_load is boot-only and not re-applied. */
void playlist_config_apply(void);
void playlist_shutdown(void);
void playlist_reload(void);

int playlist_count(void);
int playlist_idx(void); // -1 if empty
const char *playlist_at(int idx); // NULL if out of range
const char *playlist_current_path(void); // NULL if empty
const char *playlist_name(void); // display name
const char *playlist_src_path(void); // canonical .lst path, "" if none
int playlist_is_source(void); // autogenerated mirror?

/** IPC read snapshot.
 * Render thread is the sole writer. IPC thread reads an immutable deep copy
 * (snapshot) republished once per frame when dirty. Variable-length entries
 * iterated under a short-lived lock. */
struct playlist_view {
	int count;
	int index; // -1 if empty
	int is_shuffled;
	int is_locked;
	int is_source;
	char name[256];
	char src_path[1024];
	char current_path[1024]; // "" if empty
	char undo_basename[256]; // "" if nothing queued to undo
	char undo_lane_label[16]; // " (from global)" or ""
};

void playlist_mark_dirty(void);
void playlist_snapshot_sync(void);
void playlist_snapshot_get(struct playlist_view *out);
int playlist_snapshot_lock(int *out_index); // returns count
const char *playlist_snapshot_entry(int idx); // NULL out of range
void playlist_snapshot_unlock(void);

int playlist_is_shuffled(void);
void playlist_set_shuffled(int on);
int playlist_is_locked(void);
void playlist_set_locked(int locked);

void playlist_shuffle(void);
void playlist_next(void);
void playlist_prev(void);
void playlist_set_idx(int idx); // clamps to valid range

/** Load the current index's preset into visualizer. smooth=true uses
 * soft cut, smooth=false snaps. Updates transition state and arms the
 * preset-age timer. */
void playlist_load_current(bool smooth);

void playlist_reset_preset_timer(void);

/** Wall-clock seconds since the current preset was loaded. Used by the
 * per-frame auto-advance check. */
double playlist_preset_age_seconds(void);

/** Auto-advance interval, seeded from visualizer's value. */
void playlist_set_auto_advance(double seconds);
double playlist_auto_advance_seconds(void);
double playlist_configured_duration(void);
/** Engine-owns-procession switch. Host wall-clock stands down when set. */
void playlist_set_engine_driven(int on);

/** Request an engine-driven advance. hard_cut picks a hard cut, else soft. */
void playlist_request_advance(int hard_cut);
/** Poll the pending engine advance, clearing it.
 * @returns 0 = none. 1 = soft. 2 = hard. */
int playlist_poll_advance(void);

/** The auto-advance decision. Render prologue calls this each frame
 * and advances if true. */
bool playlist_should_auto_advance(void);

/** Display text for the in-flight preset transition. Empty string if no
 * transition is pending. Used by the transition tracker to apply the
 * text to the overlay's preset slot when the soft cut completes. */
const char *playlist_transition_text(void);

/** True if a soft-cut transition is currently in flight. Used by the
 * transition tracker and reported to the pacer for edge detect. */
int playlist_transition_in_progress(void);

/** Wall-clock seconds since the in-flight transition started. Undefined
 * when no transition is in progress. */
double playlist_transition_elapsed_seconds(void);

/** Clear the in-flight transition flag. */
void playlist_clear_transition(void);

/** Load playlist from file. Detects source-mirror sentinel, parses
 * #blacklist section, filters against global blacklist. */
int playlist_load_file(const char *path);

/** Save playlist to file (active entries plus #blacklist section) */
int playlist_save_file(const char *path);

/** Merge presets from a directory or .lst file into current playlist.
 * Skips entries already present, per-playlist blacklisted, or globally
 * blacklisted. */
int playlist_merge_file(const char *path);

/** Recursively scan a directory for preset files */
void playlist_scan_directory(const char *dir);

/** Add preset_path to playlist <n>, prepending if prepend=1 or
 * appending otherwise. On failure, writes a human-readable reason to
 * err and errlen. @returns 1 on success, 0 on failure. */
int playlist_add_to_file(const char *name, const char *preset_path,
                          int prepend, char *err, int errlen);

/** Resolve a playlist name to its canonical .lst path under <config_dir>/playlists/. */
void playlist_path_for_name(const char *name, char *out, size_t outlen);

/** Generate source-mirror playlists under <config_dir>/playlists/, one per
 * subdirectory of presets_dir. Skips names claimed by user-owned files. */
void playlist_rebuild_source_mirrors(void);

/** Check first line of `path` for SOURCE_PLAYLIST_SENTINEL.
 * @returns 1 if the file exists and starts with the sentinel. */
int playlist_file_has_sentinel(const char *path);

/** Per-playlist or global (system-wide) with single-level undo across
 * both. global=1 targets the system-wide lane. @returns >0 on success
 * with the basename written to out_name, 0 on no-op. */
int playlist_blacklist_current(int global, char *out_name, int outlen);

/** Undo the most recent blacklist. @returns 0 if nothing to undo. On
 * success, writes the restored preset's basename and lane label to the
 * caller-provided buffer for IPC reply formatting. */
int playlist_undo_blacklist(char *out_name, int outlen,
                             const char **out_lane_label);

/** Reorder the in-memory playlist so the currently-running preset moves
 * to index 0. @returns 0 if no preset is running, 1 if already at top
 * (no-op success), 2 if rotation was performed. */
int playlist_pin_current_to_top(void);

int playlist_is_globally_blacklisted(const char *path);

/** Inspect the queued single-level undo state. Used by `ipc_undo` to format
 * the synchronous reply text before the PENDING_UNDO action actually
 * fires on the render thread. `lane_label` returns " (from global)" for the
 * global lane, "" for the per-playlist lane.
 * @returns NULL if nothing is queued for undo. */
const char *playlist_pending_undo_basename(void);
const char *playlist_pending_undo_lane_label(void);

/** Auto-load (setup-time).
 * Honours the playlist slice's auto-load setting (`playlist.auto_load`)
 * with autosave-prefer semantics. out_from_autosave (optional) receives 1
 * if the .autosave sibling was used.
 * @returns 1 if a playlist was loaded, 0 if no auto-load configured or
 * the configured target couldn't be loaded. */
int playlist_auto_load(int *out_from_autosave);

/** If nothing got auto-loaded, fall back to scanning presets_dir into the
 * in-memory playlist. Sets name="default" and src_path="". */
void playlist_scan_presets_dir_fallback(void);

/** Write the current playlist state to its .autosave sibling. Suppressed
 * for source-mirror playlists and when no source path is set. Called by
 * `apply_pending` after each modifying op. */
void playlist_autosave_current(void);

/** Resolve a canonical .lst path to its .autosave sibling path. Used by
 * PENDING_PLAYLIST_LOAD's autosave-prefer check. @returns 1 on success, 0 if
 * source is empty or output would exceed outlen. */
int playlist_autosave_path_for(const char *canonical, char *out, int outlen);

/** Set the playlist's display name and source path. Called after a
 * successful PENDING_PLAYLIST_LOAD or PENDING_PLAYLIST_NEW so the playlist's
 * identity reflects the new file. */
void playlist_set_name_from_path(const char *canonical);
void playlist_set_src_path(const char *canonical);
void playlist_clear_src_path(void);

/** Direct name setter (for `playlist new <name> [dir]` IPC which provides
 * an explicit name rather than deriving it from a path). */
void playlist_set_name(const char *name);

/** Reset the in-memory playlist: clear array, clear per-playlist
 * blacklist, name="default", src_path="", is_source=false. Used by
 * PENDING_PLAYLIST_NEW and PENDING_PLAYLIST_RESCAN before loading the new content. */
void playlist_reset(void);

/** Append <name> to the access log, suppressing immediate duplicates of
 * the most recent entry. Best-effort. Errors are silent. The access log
 * is a UX feature, not a correctness invariant. */
void playlist_access_log_append(const char *name);

/** Show playlists in <config_dir>/playlists/ by access-log recency.
 * Default: most-recently-loaded.
 * All: every .lst in the dir, logged ones first (newest to oldest),
 * then never-loaded ones sorted alphabetically. The current playlist
 * is marked with a leading "* ". */
int playlist_render_list_reply(char *buf, int buflen, int show_all);

/** Non-mutating basename - returns pointer into `path` past last '/'. */
const char *path_basename(const char *path);
/** Write basename of `path` into `out`, stripping the last extension. */
void path_basename_no_ext(const char *path, char *out, size_t outlen);

#ifdef __cplusplus
}
#endif

#endif
